export const DASHBOARD_ROOT = "/dashboard";

export const VIEWS = [
  {
    viewId: "overview",
    group: "overview",
    path: `${DASHBOARD_ROOT}/overview`,
    kind: "overview",
  },
  {
    viewId: "revenue_trend",
    group: "revenue",
    path: `${DASHBOARD_ROOT}/revenue/trend`,
    apiPath: "/period",
    kind: "series",
    chartType: "area",
    xField: "period",
    valueField: "revenue",
    acceptsDateRange: true,
    extraParams: { granularity: "monthly" },
  },
  {
    viewId: "revenue_destination",
    group: "revenue",
    path: `${DASHBOARD_ROOT}/revenue/destination`,
    apiPath: "/by-destination",
    kind: "breakdown",
    chartType: "bar",
    xField: "destination",
    valueField: "revenue",
    acceptsDateRange: true,
  },
  {
    viewId: "revenue_channel",
    group: "revenue",
    path: `${DASHBOARD_ROOT}/revenue/channel`,
    apiPath: "/by-channel",
    kind: "breakdown",
    chartType: "bar",
    xField: "channel",
    valueField: "revenue",
    acceptsDateRange: true,
  },
  {
    viewId: "revenue_segment",
    group: "revenue",
    path: `${DASHBOARD_ROOT}/revenue/segment`,
    apiPath: "/by-segment",
    kind: "breakdown",
    chartType: "pie",
    xField: "segment",
    valueField: "revenue",
    acceptsDateRange: true,
  },
  {
    viewId: "revenue_discount",
    group: "revenue",
    path: `${DASHBOARD_ROOT}/revenue/discount`,
    apiPath: "/discount-impact",
    kind: "breakdown",
    chartType: "bar",
    xField: "discount_band",
    valueField: "revenue",
    acceptsDateRange: true,
  },
  {
    viewId: "forecast",
    group: "revenue",
    path: `${DASHBOARD_ROOT}/forecast`,
    kind: "forecast",
  },
  {
    viewId: "agent_performance",
    group: "operations",
    path: `${DASHBOARD_ROOT}/agents`,
    apiPath: "/agent-performance",
    kind: "breakdown",
    chartType: "bar",
    xField: "agent_name",
    valueField: "revenue",
    acceptsDateRange: true,
  },
  {
    viewId: "bookings",
    group: "operations",
    path: `${DASHBOARD_ROOT}/bookings`,
    apiPath: "/bookings/volume",
    kind: "series",
    chartType: "line",
    xField: "date",
    valueField: "bookings",
    acceptsDateRange: true,
  },
  {
    viewId: "booking_cancellation",
    group: "operations",
    path: `${DASHBOARD_ROOT}/bookings/cancellation`,
    apiPath: "/bookings/cancellation-rate",
    kind: "scalar",
    acceptsDateRange: true,
  },
  {
    viewId: "customers",
    group: "customers",
    path: `${DASHBOARD_ROOT}/customers`,
    apiPath: "/customers/segment-distribution",
    kind: "breakdown",
    chartType: "pie",
    xField: "segment",
    valueField: "customers",
    acceptsDateRange: false,
  },
  {
    viewId: "customer_top",
    group: "customers",
    path: `${DASHBOARD_ROOT}/customers/top`,
    apiPath: "/customers/top",
    kind: "breakdown",
    chartType: "bar",
    xField: "name",
    valueField: "total_spent_idr",
    acceptsDateRange: false,
  },
  {
    viewId: "churn",
    group: "customers",
    path: `${DASHBOARD_ROOT}/churn`,
    kind: "churn",
  },
  {
    viewId: "campaigns",
    group: "marketing",
    path: `${DASHBOARD_ROOT}/campaigns`,
    apiPath: "/campaigns/performance",
    kind: "breakdown",
    chartType: "bar",
    xField: "campaign_name",
    valueField: "conversions",
    acceptsDateRange: true,
  },
  {
    viewId: "destinations",
    group: "catalog",
    path: `${DASHBOARD_ROOT}/destinations`,
    apiPath: "/destinations/popularity-vs-bookings",
    kind: "breakdown",
    chartType: "bar",
    xField: "destination",
    valueField: "bookings",
    acceptsDateRange: true,
  },
  {
    viewId: "packages",
    group: "catalog",
    path: `${DASHBOARD_ROOT}/packages`,
    apiPath: "/packages/top",
    kind: "breakdown",
    chartType: "bar",
    xField: "package_name",
    valueField: "revenue",
    acceptsDateRange: false,
  },
  {
    viewId: "partners",
    group: "catalog",
    path: `${DASHBOARD_ROOT}/partners`,
    apiPath: "/partners/hotels/top",
    kind: "breakdown",
    chartType: "bar",
    xField: "hotel_name",
    valueField: "revenue",
    acceptsDateRange: false,
  },
  {
    viewId: "reviews",
    group: "catalog",
    path: `${DASHBOARD_ROOT}/reviews`,
    apiPath: "/reviews/sentiment-summary",
    kind: "breakdown",
    chartType: "pie",
    xField: "sentiment",
    valueField: "total",
    acceptsDateRange: true,
  },
];

export const VIEW_GROUP_ORDER = [
  "overview", "revenue", "operations", "customers", "marketing", "catalog",
];

export const VIEWS_BY_ID = Object.fromEntries(
  VIEWS.map((view) => [view.viewId, view])
);

export const VIEW_GROUPS = VIEW_GROUP_ORDER.map((name) => ({
  name,
  views: VIEWS.filter((view) => view.group === name),
})).filter((group) => group.views.length > 0);
